# Generated by Django 5.0.3 on 2024-03-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('price', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=50)),
                ('lte_exists', models.BooleanField()),
            ],
        ),
    ]
